//! Byte-identical PGAS TRANSITION-DENSITY baseline gate — the oracle for the
//! continuous, `s*dt`/FP-sensitive quantity that the forward trajectory and
//! bootstrap-PF marginal gates (both integer-valued) cannot see.
//!
//! `log_transition_density_substep` is `gamma`/`Poisson` log-density of the
//! per-substep flows given the rate at `t = t_start + s*dt` (the canonical
//! substep-time convention — `pgas.rs:716`, `chain_binomial.rs` now matches it).
//! It is the quantity a ULP shift in the realized `dt` (the substep-size FP fix,
//! 16a61c8) or in the substep time (the `s*dt` convention) would move. So this is
//! the gate that would actually catch a regression in that class, on a SEASONAL
//! model at fractional `dt` where time-inhomogeneous forcing makes the substep
//! time load-bearing.
//!
//! `simulate_reference` generates a latent reference trajectory deterministically
//! from a fixed seed; the total transition log-density of that trajectory is a
//! deterministic scalar. Pinned here byte-for-byte.
//!
//! The model is loaded from the committed `seasonal_drift` corner-case IR
//! (regenerated by `make update-corner-golden`). Baselines are
//! machine/toolchain-specific (libm) — a dev ratchet, like the sibling gates.
//! Re-capture:
//!   CAMDL_CAPTURE_BASELINE=1 cargo test -p sim --test gate_pgas_density_baseline -- --nocapture

use std::path::PathBuf;
use std::sync::Arc;

use sim::{
    compiled_model::CompiledModel,
    inference::pgas::{log_transition_density_substep, simulate_reference},
    rng::StatefulRng,
};

const SEED: u64 = 7;

fn ir_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../tests/fixtures/corner_cases/ir/seasonal_drift.ir.json")
}

fn load_seasonal() -> Arc<CompiledModel> {
    let contents = std::fs::read_to_string(ir_path())
        .unwrap_or_else(|e| panic!("read {:?}: {}", ir_path(), e));
    let model = ir::from_str(&contents).expect("parse seasonal_drift IR");
    Arc::new(CompiledModel::new(model).expect("compile seasonal_drift"))
}

/// Total transition log-density of a deterministic reference trajectory generated
/// at `dt`. The density time is `t_start + s*dt` — the convention under test.
fn reference_total_logdensity(dt: f64) -> f64 {
    let compiled = load_seasonal();
    let params = compiled.default_params.clone();
    let t_start = compiled.model.simulation.t_start;
    let t_end = compiled.model.simulation.t_end;
    let mut rng = StatefulRng::new(SEED);
    let traj = simulate_reference(&compiled, &params, t_end, dt, sim::rng::BinomialAlgorithm::default(), &mut rng)
        .expect("simulate_reference on seasonal_drift");

    let mut total = 0.0;
    for (s, rec) in traj.substeps.iter().enumerate() {
        let t = t_start + s as f64 * dt;
        total += log_transition_density_substep(
            &compiled, &rec.counts_before, &rec.flows, &rec.gammas, &params, t, dt, None,
        )
        .expect("finite per-substep density");
    }
    total
}

// (label, dt) -> total transition log-density, captured on the dev machine.
const BASELINES: &[(&str, f64, f64)] = &[
    ("seasonal_drift", 0.1, -1.47985724769508361e4),
    ("seasonal_drift", 1.0, -7.68251471594024315e3),
];

#[test]
fn pgas_density_is_deterministic() {
    // Precondition for a byte-identical baseline: same seed → identical density.
    let a = reference_total_logdensity(0.1);
    let b = reference_total_logdensity(0.1);
    assert_eq!(a.to_bits(), b.to_bits(), "reference density must be deterministic ({a} vs {b})");
}

#[test]
fn pgas_density_baselines_hold() {
    let capture = std::env::var("CAMDL_CAPTURE_BASELINE").is_ok();
    let cases: &[(&str, f64)] = &[
        ("seasonal_drift", 0.1), // fractional dt — s*dt is load-bearing here
        ("seasonal_drift", 1.0), // integer dt — s*dt == accumulation
    ];
    let mut captured = Vec::new();
    let mut missing = Vec::new();

    for (label, dt) in cases {
        let total = reference_total_logdensity(*dt);
        assert!(total.is_finite(), "{label}@dt={dt}: total density must be finite, got {total}");
        if capture {
            captured.push(format!("    (\"{label}\", {dt:?}, {total:.17e}),"));
            continue;
        }
        match BASELINES.iter().find(|(l, d, _)| l == label && *d == *dt).map(|(_, _, v)| *v) {
            Some(expected) => assert_eq!(
                total.to_bits(),
                expected.to_bits(),
                "PGAS DENSITY CHANGED for {label}@dt={dt}: a refactor moved the transition \
                 log-density (got {total:.17e}, expected {expected:.17e})"
            ),
            None => missing.push(format!("{label}@dt={dt}")),
        }
    }

    if capture {
        eprintln!("\n// <<CAPTURED-BASELINES>> — paste into BASELINES:");
        for line in &captured {
            eprintln!("{line}");
        }
        return;
    }
    assert!(missing.is_empty(), "no baseline for: {missing:?} — run with CAMDL_CAPTURE_BASELINE=1");
}
