//! Tier-5 external-oracle cross-validation for stratified lineage attribution
//! (2026-05-19 individual-sampling-layer proposal, §"Validation" Tier 5).
//!
//! Cross-validates camdl's contact-structured parent attribution against an
//! independent lineage-aware simulator (VGsim or MASTER) on the *stratified*
//! `spatial_lineage` scenario — the case the proposal calls the "real
//! deliverable" because it carries the silent-wrong-answer risk.
//!
//! Same offline-fixture pattern as the pomp / scipy / numpy oracle tests
//! (`periodic_bspline_oracle.rs`, `fourier_oracle.rs`): the reference TSV is
//! committed under `tests/fixtures/` and CI never needs the oracle installed.
//! The committed fixture is generated by
//! `scripts/gen_spatial_lineage_vgsim_fixture.py`.
//!
//! ## Status: SCAFFOLDED, awaiting a real oracle run
//!
//! VGsim / MASTER were not installable in the environment where Phase 2
//! landed (no network access, no BEAST2). Per the proposal's "do not
//! fabricate reference data" rule, the committed fixture is a clearly-marked
//! PLACEHOLDER. This test detects the placeholder (the `# PLACEHOLDER` marker
//! on line 1) and SKIPS — it does not assert against fabricated numbers. The
//! moment a human runs the generator and commits a real fixture (which drops
//! the marker), this test ACTIVATES with no code change.

use std::cell::RefCell;
use std::collections::BTreeMap;
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::rc::Rc;

use sim::{
    compiled_model::CompiledModel,
    config::GillespieConfig,
    gillespie::run_gillespie_with_observer,
    lineage::{LineListEntry, LineListWriter, LineageObserver, ParentRef},
};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("tests/fixtures")
}

#[derive(Clone)]
struct VecWriter {
    entries: Rc<RefCell<Vec<LineListEntry>>>,
}
impl VecWriter {
    fn new() -> Self {
        VecWriter { entries: Rc::new(RefCell::new(Vec::new())) }
    }
}
impl LineListWriter for VecWriter {
    fn init(&mut self) -> Result<(), sim::SimError> {
        Ok(())
    }
    fn write(&mut self, e: &LineListEntry) -> Result<(), sim::SimError> {
        self.entries.borrow_mut().push(e.clone());
        Ok(())
    }
    fn finish(&mut self) -> Result<(), sim::SimError> {
        Ok(())
    }
}

/// True if the fixture is the un-generated placeholder (line 1 carries the
/// `# PLACEHOLDER` marker). When true, the test skips.
fn is_placeholder(path: &Path) -> bool {
    let Ok(f) = File::open(path) else { return true };
    let mut first = String::new();
    if BufReader::new(f).read_line(&mut first).is_err() {
        return true;
    }
    first.contains("PLACEHOLDER")
}

/// Parse the oracle TSV into `oracle[(focal_deme, parent_deme)] = probability`.
fn read_oracle(path: &Path) -> BTreeMap<(u32, u32), f64> {
    let f = File::open(path).unwrap();
    let mut out = BTreeMap::new();
    for line in BufReader::new(f).lines() {
        let line = line.unwrap();
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') || t.starts_with("focal_deme") {
            continue;
        }
        let c: Vec<&str> = t.split('\t').collect();
        assert_eq!(c.len(), 3, "expected 3 columns, got {:?}", c);
        let focal: u32 = c[0].parse().unwrap();
        let parent: u32 = c[1].parse().unwrap();
        let prob: f64 = c[2].parse().unwrap();
        out.insert((focal, parent), prob);
    }
    out
}

/// camdl's own conditional infector-deme distribution P(parent_deme |
/// focal_deme), pooled over many replicates of `spatial_lineage`. This is the
/// quantity the oracle must agree with.
fn camdl_conditional_distribution() -> BTreeMap<(u32, u32), f64> {
    let path = fixtures_dir().join("spatial_lineage.ir.json");
    let contents = std::fs::read_to_string(&path).unwrap();
    let mut m: ir::Model = ir::from_str(&contents).unwrap();
    for p in &mut m.parameters {
        match p.name.as_str() {
            "beta" => p.value = Some(0.6),
            "gamma" => p.value = Some(0.2),
            _ => {}
        }
    }

    // counts[(focal, parent)] = number of transmission events.
    let mut counts: BTreeMap<(u32, u32), u64> = BTreeMap::new();
    for seed in 0..2_000u64 {
        let compiled = CompiledModel::new(m.clone()).unwrap();
        let params = compiled.default_params.clone();
        let (initial_int, _) = compiled.initial_state(&params).unwrap();
        let collector = VecWriter::new();
        let buf = collector.entries.clone();
        let mut observer =
            LineageObserver::new(&compiled, seed, &initial_int, collector).unwrap();
        let cfg = GillespieConfig { t_start: 0.0, t_end: 8.0, output_dt: None };
        run_gillespie_with_observer(&compiled, &params, seed, &cfg, Some(&mut observer)).unwrap();
        observer.finish().unwrap();
        for e in buf.borrow().iter() {
            if let ParentRef::Individual(_) = e.parent {
                let parent = e.parent_deme.unwrap();
                *counts.entry((e.deme, parent)).or_default() += 1;
            }
        }
    }

    // Normalise within each focal deme to a conditional distribution.
    let mut totals: BTreeMap<u32, u64> = BTreeMap::new();
    for ((focal, _), n) in &counts {
        *totals.entry(*focal).or_default() += n;
    }
    counts
        .into_iter()
        .map(|((focal, parent), n)| {
            ((focal, parent), n as f64 / totals[&focal] as f64)
        })
        .collect()
}

#[test]
fn tier5_stratified_attribution_matches_external_oracle() {
    let fixture = fixtures_dir().join("spatial_lineage_vgsim.tsv");
    if is_placeholder(&fixture) {
        eprintln!(
            "SKIP tier5_stratified_attribution_matches_external_oracle: \
             {} is the un-generated PLACEHOLDER. Run \
             scripts/gen_spatial_lineage_vgsim_fixture.py with VGsim/MASTER \
             installed and commit the real fixture to activate this test.",
            fixture.display()
        );
        return;
    }

    let oracle = read_oracle(&fixture);
    assert!(!oracle.is_empty(), "oracle fixture parsed empty");
    let camdl = camdl_conditional_distribution();

    // Tolerance covers both simulators' Monte-Carlo error on the conditional
    // probabilities. With ≥10⁶ oracle events and ~10⁶ camdl events the
    // sampling error on each probability is well under 1e-2; 3e-2 is a safe
    // band that still rejects a wrong (e.g. transposed-C or uniform)
    // attribution, whose probabilities differ by tenths.
    const TOL: f64 = 3e-2;
    let mut max_diff = 0.0f64;
    for ((focal, parent), p_oracle) in &oracle {
        let p_camdl = camdl.get(&(*focal, *parent)).copied().unwrap_or(0.0);
        let diff = (p_camdl - p_oracle).abs();
        max_diff = max_diff.max(diff);
        assert!(
            diff < TOL,
            "P(parent={parent} | focal={focal}): camdl {:.4} vs oracle {:.4}, \
             |diff| {:.4} exceeds tolerance {:.4}",
            p_camdl,
            p_oracle,
            diff,
            TOL
        );
    }
    eprintln!("tier5 oracle agreement: max |diff| = {:.4} (tol {:.4})", max_diff, TOL);
}
