#!/usr/bin/env python3
"""Generate parametric toy SEIR spatial+age .camdl models for scaling benches.

The toy model faithfully reproduces the force-of-infection (FOI) *shape* of the
real Kano measles model (`playpen-camdl-measles/.../kano_lga_seirv.camdl`): the
per-patch aggregates `N[l]`, `I_agg[l]` and the spatial coupling **sum inside the
infection rate** — `kappa * sum(q in patch, W[l,q]*I_agg[q]/N[q])`. That sum is
what the OCaml compiler flat-inlines into every `(patch,age)` infection rate tree
(and into each free parameter's gradient tree), producing the observed IR blowup.

Knobs (the experimental axes):
  P         number of patches (spatial units) — the dominant O(P^2) axis
  A         number of age groups
  coupling  'on'  → include the kappa*sum(q...) spatial term  (O(P) per infection)
            'off' → drop it (control: isolates the spatial term as the O(P^2) source)
  grad      'full'    → FOI params (R0,gamma,kappa,amplitude,iota) are FREE params,
                        so camdlc emits a rate_grad tree per param (IR-size multiplier)
            'minimal' → those constants are baked as literals, no free params,
                        no rate_grad (isolates the bare rate-tree cost)

Note: rate_grad is only consumed by gradient-based inference (PGAS/NUTS). Forward
`simulate` evaluates only `rate`, so the `grad` knob inflates IR/compile/parse/RSS
but NOT forward-sim stepping. That separation is intentional and measured.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _patch_names(P: int) -> list[str]:
    return [f"p{i}" for i in range(P)]


def _age_names(A: int) -> list[str]:
    return [f"a{i}" for i in range(A)]


def _w_matrix(P: int) -> str:
    """Row-normalised off-diagonal coupling: W[i][j] = 1/(P-1) for i!=j, 0 on diag.

    For P==1 there is no coupling target; callers should use coupling='off'.
    """
    if P == 1:
        return "[[0.0]]"
    off = round(1.0 / (P - 1), 8)
    rows = []
    for i in range(P):
        vals = [("0.0" if j == i else str(off)) for j in range(P)]
        rows.append("[" + ", ".join(vals) + "]")
    indent = ",\n" + " " * 24
    return "[" + indent.join(rows) + "]"


def _w_matrix_sparse(P: int, k: int) -> str:
    """Sparse ring coupling: patch i couples only to its k nearest neighbours
    (k//2 each side, wrapping), row-normalised over those k; 0 elsewhere.

    The realistic national-scale shape (local neighbour mixing) — a literal W
    with P*k nonzeros and P^2 - P*k structural zeros. The dense P-term FOI
    Reduce the expander emits collapses to a k-term Reduce once the
    constant-fold pass resolves the zero W cells and drops them.
    """
    half = max(1, k // 2)
    rows = []
    for i in range(P):
        nbrs = set()
        for d in range(1, half + 1):
            nbrs.add((i - d) % P)
            nbrs.add((i + d) % P)
        nbrs.discard(i)
        w = round(1.0 / len(nbrs), 8) if nbrs else 0.0
        vals = [(str(w) if j in nbrs else "0.0") for j in range(P)]
        rows.append("[" + ", ".join(vals) + "]")
    indent = ",\n" + " " * 24
    return "[" + indent.join(rows) + "]"


def gen_camdl(P: int, A: int, coupling: str, grad: str, observe: bool = False,
              coupling_degree: int = 0) -> str:
    assert coupling in ("on", "off")
    assert grad in ("full", "minimal")
    if coupling == "on" and P < 2:
        raise ValueError("coupling='on' requires P >= 2")

    patches = _patch_names(P)
    ages = _age_names(A)
    full = grad == "full"

    L: list[str] = []
    L.append(f"# Auto-generated scaling toy model: P={P} A={A} "
             f"coupling={coupling} grad={grad}")
    L.append("# Generated by scripts/gen_scaling_models.py — do not edit by hand.")
    L.append("time_unit = 'days")
    L.append("")
    L.append("compartments { S, E, I, R }")
    L.append("")
    L.append("dimensions {")
    L.append(f"  patch = [{', '.join(patches)}]")
    L.append(f"  age   = [{', '.join(ages)}]")
    L.append("}")
    L.append("")
    L.append("stratify(by = patch)")
    L.append("stratify(by = age)")
    L.append("")
    # Per-patch aggregates — the big PopSum trees (O(A) and O(C*A)).
    L.append("let N[l in patch]     = sum(a in age, S[l, a] + E[l, a] + I[l, a] + R[l, a])")
    L.append("let I_agg[l in patch] = sum(a in age, I[l, a])")
    L.append("")

    # Parameters / constants depending on grad knob.
    if full:
        L.append("parameters {")
        L.append("  R0        : positive    in [5.0, 30.0]")
        L.append("  sigma     : rate        in [0.05, 0.30]")
        L.append("  gamma     : rate        in [0.05, 0.30]")
        if coupling == "on":
            L.append("  kappa     : probability in [0.0, 1.0]")
        L.append("  amplitude : probability in [0.0, 0.7]")
        L.append("  iota      : positive    in [1e-10, 1e-3]")
        L.append("}")
        L.append("")
        L.append("let beta = R0 * gamma")
        L.append("let seas = 1.0 - amplitude + amplitude * 2.0 * school(t)")
        iota_term = "iota"
        kappa_term = "kappa"
        sigma_rate = "sigma"
        gamma_rate = "gamma"
    else:
        # Everything baked to literals: zero free params → no rate_grad.
        L.append("let beta = 2.145")              # ~ R0=15 * gamma=0.143
        L.append("let seas = 0.75 + 0.5 * school(t)")  # amplitude=0.25 baked
        iota_term = "0.0000001"
        kappa_term = "0.05"
        sigma_rate = "0.125"
        gamma_rate = "0.143"

    L.append("")
    L.append("forcing {")
    L.append("  school : periodic 'ratio {")
    L.append("    period = 365.25 'days")
    L.append("    step   = 1 'days")
    L.append("    on     = [0:182]")
    L.append("  }")
    L.append("}")
    L.append("")

    if coupling == "on":
        w_lit = _w_matrix_sparse(P, coupling_degree) if coupling_degree > 0 else _w_matrix(P)
        L.append("tables {")
        L.append(f"  W : patch × patch = {w_lit}")
        L.append("}")
        L.append("")

    # ── Transitions ──────────────────────────────────────────────────────────
    L.append("transitions {")
    foi_local = f"(I_agg[l] + {iota_term}) / N[l]"
    if coupling == "on":
        if coupling_degree > 0:
            # Guarded form: W[l,q] * (if N[q] > 0 then I_agg[q]/N[q] else 0).
            # Makes the constant-fold sound — a zero-W term folds 0*(finite)->0
            # in one step (the division lives inside the guard, never reached
            # when the term is zeroed), so dropping it is byte-identical.
            inner = "(if N[q] > 0 then I_agg[q] / N[q] else 0.0)"
        else:
            inner = "I_agg[q] / N[q]"
        foi_spatial = (f"\n      + {kappa_term} * "
                       f"sum(q in patch, W[l, q] * {inner})")
    else:
        foi_spatial = ""
    L.append("  infection[l in patch, a in age] : S[l, a] --> E[l, a]")
    L.append(f"    @ beta * seas * S[l, a] * (")
    L.append(f"        {foi_local}{foi_spatial}")
    L.append("      )")
    L.append("")
    L.append(f"  progression[l in patch, a in age] : E[l, a] --> I[l, a] @ {sigma_rate} * E[l, a]")
    L.append(f"  recovery[l in patch, a in age]    : I[l, a] --> R[l, a] @ {gamma_rate} * I[l, a]")
    L.append("}")
    L.append("")

    # Observation model (opt-in via --observe) — a single weekly stream over
    # *total* infectious prevalence. Bare `I` sums over all strata (spec §11
    # "bare = sum over ALL strata"); we use `prevalence(I)` rather than
    # `incidence(infection)` because the latter currently fails to resolve a
    # base (pre-expansion) transition name in a stratified model (E507). For
    # inference *profiling* the observable is irrelevant — the particle filter
    # steps the full model regardless. Literal reporting params (rho=0.5, NB
    # dispersion r=5) keep scaling benches byte-identical without --observe;
    # PMMH/PGAS estimate the existing free FOI params (R0, gamma, …).
    if observe:
        L.append("observations {")
        L.append("  weekly_cases : {")
        L.append("    projected  = prevalence(I)")
        L.append("    every      = 7 'days")
        L.append("    likelihood = neg_binomial(mean = 0.5 * projected, r = 5.0)")
        L.append("  }")
        L.append("}")
        L.append("")

    # ── Init (all positive so every source group is active → full eval cost) ──
    L.append("init {")
    L.append("  S[l in patch, a in age] = 900")
    L.append("  E[l in patch, a in age] = 10")
    L.append("  I[l in patch, a in age] = 10")
    L.append("  R[l in patch, a in age] = 80")
    L.append("}")
    L.append("")
    L.append("simulate {")
    L.append("  from = 0 'days")
    L.append("  to   = 365 'days")
    L.append("}")
    L.append("")

    # Scenario only needed when there are free params to pin.
    if full:
        L.append("scenarios {")
        L.append("  baseline {")
        L.append('    label = "scaling toy baseline"')
        L.append("    set = {")
        L.append("      R0        = 15.0")
        L.append("      sigma     = 0.125")
        L.append("      gamma     = 0.143")
        if coupling == "on":
            L.append("      kappa     = 0.05")
        L.append("      amplitude = 0.25")
        L.append("      iota      = 1e-7")
        L.append("    }")
        L.append("  }")
        L.append("}")
        L.append("")

    return "\n".join(L)


def _c_matrix(A: int) -> str:
    """Row-stochastic assortative age contact matrix (diag-heavy, rows sum to 1
    → spectral radius 1, already normalised like Klein's normalize_C)."""
    if A == 1:
        return "[[1.0]]"
    diag, off = 0.6, round(0.4 / (A - 1), 8)
    rows = ["[" + ", ".join((str(diag) if j == i else str(off)) for j in range(A)) + "]"
            for i in range(A)]
    return "[" + ", ".join(rows) + "]"


def gen_polio(P: int, A: int, grad: str, observe: bool = False,
              coupling_degree: int = 0, to: str = "12 'years",
              immunity: float = 0.8, iota: float = 0.0, pop: int = 20010) -> str:
    """cVDPV2 metapop faithfully mirroring Daniel Klein's Sokoto model
    (gh#207/#209 + his exp-07 codegen): per (patch, age) stratum S, I_v
    (vaccine-derived), I_c (circulating), R, plus a single un-stratified AFP
    paralysis accumulator.

    - Two infected classes; I_v reverts to I_c at rate mu_rev.
    - Within-patch force-of-infection mixes ages through a contact matrix C_age
      (sum(b in age, C_age[a,b]*I[l,b]/N_age[l,b])).
    - Cross-patch spread via gravity-kernel import transitions (imp_I_v/imp_I_c),
      a guarded Reduce the sparse-coupling fold collapses O(P²)→O(P·k).
    - Age-split waning (R→S), aging (a_i→a_{i+1}), births into the youngest age,
      per-(comp,age) mortality.
    - AFP observed as monthly incidence(afp_influx), neg_binomial.

    At P=244, A=3: 4·244·3 + 1 = 2,929 stratified compartments + AFP. (Klein's
    headline 4,393 reflects his finer ward/age split; this matches the FOI and
    transition *shape* — age-mixing + gravity fold + full demography — which is
    what drives per-step eval and RSS.) Deliberately omitted (need his private
    anchors, not load-bearing for the scaling regime): timed SIA interventions
    and the real per-LGA gravity/contact data — here W is a synthetic top-k ring
    and C is assortative.

    grad='minimal' bakes literals into rate positions → compile with
    --no-dim-check (bare literals are dimensionless; E300 otherwise).
    """
    assert grad in ("full", "minimal")
    if P < 2 and coupling_degree > 0:
        raise ValueError("coupling requires P >= 2")
    patches = _patch_names(P)
    ages = _age_names(A)
    full = grad == "full"
    comps = ["S", "I_v", "I_c", "R"]
    pf = (lambda name, lit: name if full else lit)

    gamma_v_t = pf("gamma_v", "0.05")
    gamma_c_t = pf("gamma_c", "0.05")
    pri_t     = pf("p_recover_immune", "0.8")
    murev_t   = pf("mu_rev", "0.02")
    rho_t     = pf("rho_afp", "0.005")
    k_t       = pf("k", "5.0")
    kappa_t   = pf("kappa", "0.05")
    aging_t   = pf("aging_rate", "0.0005")
    birth_t   = pf("birth_rate", "0.0001")
    omega_t   = {a: pf(f"omega_{a}", "0.005") for a in ages}
    mu_t      = {a: pf(f"mu_{a}", "0.0002") for a in ages}
    iota_t    = pf("iota", str(iota))

    L: list[str] = []
    L.append(f"# Auto-generated polio-cVDPV2 metapop: P={P} A={A} grad={grad}")
    L.append("# Generated by scripts/gen_scaling_models.py --shape polio — do not edit by hand.")
    L.append("time_unit = 'days")
    L.append("")
    L.append("compartments { S, I_v, I_c, R, AFP }")
    L.append("")
    L.append("dimensions {")
    L.append(f"  patch = [{', '.join(patches)}]")
    L.append(f"  age   = [{', '.join(ages)}]")
    L.append("}")
    L.append("")
    L.append("stratify(by = patch, only = [S, I_v, I_c, R])")
    L.append("stratify(by = age, only = [S, I_v, I_c, R])")
    L.append("")
    L.append("let N_age[l in patch, a in age] = S[l, a] + I_v[l, a] + I_c[l, a] + R[l, a]")
    L.append("let N_total[l in patch] = sum(a in age, N_age[l, a])")
    L.append("let I_v_total[l in patch] = sum(a in age, I_v[l, a])")
    L.append("let I_c_total[l in patch] = sum(a in age, I_c[l, a])")
    L.append("")

    if full:
        L.append("parameters {")
        L.append("  R0_c             : positive    in [1.0, 20.0]")
        L.append("  R0_v             : positive    in [0.5, 5.0]")
        L.append("  gamma_v          : rate        in [0.01, 0.2]")
        L.append("  gamma_c          : rate        in [0.01, 0.2]")
        L.append("  p_recover_immune : probability in [0.0, 1.0]")
        L.append("  mu_rev           : probability in [0.0, 0.1]")
        L.append("  rho_afp          : positive    in [1e-6, 1.0]")
        L.append("  k                : positive    in [0.1, 100.0]")
        L.append("  iota             : positive    in [0.0, 1.0]")
        L.append(f"  S0               : count       in [0, {pop}]")
        if coupling_degree > 0:
            L.append("  kappa            : rate        in [0.0, 1.0]")
        L.append("  aging_rate       : rate        in [0.0001, 0.01]")
        L.append("  birth_rate       : rate        in [0.0, 0.001]")
        for a in ages:
            L.append(f"  omega_{a:<10}     : rate        in [0.0, 0.1]")
        for a in ages:
            L.append(f"  mu_{a:<10}        : rate        in [0.0, 0.01]")
        L.append("}")
        L.append("")
        L.append("let beta_v = R0_v * gamma_v")
        L.append("let beta_c = R0_c * gamma_c")
    else:
        L.append("let beta_v = 0.1")    # R0_v=2 * gamma_v=0.05
        L.append("let beta_c = 0.3")    # R0_c=6 * gamma_c=0.05
    L.append("")

    L.append("tables {")
    if coupling_degree > 0:
        L.append(f"  W_patch : patch × patch = {_w_matrix_sparse(P, coupling_degree)}")
    L.append(f"  C_age   : age × age     = {_c_matrix(A)}")
    L.append("}")
    L.append("")

    foi_v = "beta_v * S[l, a] * sum(b in age, C_age[a, b] * I_v[l, b] / N_age[l, b])"
    # A low external force of infection `iota` (imported circulating virus) keeps
    # the circulating chain from going fully extinct — the fadeout-and-reemergence
    # term, per the single-pop cvdpv2 model and the GPEI seeding assumption.
    # `iota` is a parameter (scenarios switch it: 0 for a self-propagating
    # outbreak, >0 for the contained import-sustained endemic).
    foi_c = (f"beta_c * S[l, a] * (sum(b in age, C_age[a, b] * I_c[l, b] / N_age[l, b])"
             f" + {iota_t})")

    L.append("transitions {")
    # Within-patch FOI with age mixing; I_v can revert to I_c at rate mu_rev.
    L.append("  inf_v[l in patch, a in age] : S[l, a] --> I_v[l, a]")
    L.append(f"    @ (1 - {murev_t}) * {foi_v}")
    L.append("  inf_v_revert[l in patch, a in age] : S[l, a] --> I_c[l, a]")
    L.append(f"    @ {murev_t} * {foi_v}")
    L.append("  inf_c[l in patch, a in age] : S[l, a] --> I_c[l, a]")
    L.append(f"    @ {foi_c}")
    # Cross-patch gravity import (guarded Reduce → sparse-fold collapses O(P²)→O(P·k)).
    if coupling_degree > 0:
        for cls, tot in (("I_v", "I_v_total"), ("I_c", "I_c_total")):
            L.append(f"  imp_{cls}[l in patch, a in age] : S[l, a] --> {cls}[l, a]")
            L.append(f"    @ {kappa_t} * S[l, a] * sum(q in patch, "
                     f"W_patch[l, q] * (if N_total[q] > 0 then {tot}[q] / N_total[q] else 0.0))")
    # Recovery (I_v → immune R or back to S; I_c → R).
    L.append(f"  recover_v_immune[l in patch, a in age] : I_v[l, a] --> R[l, a] @ {gamma_v_t} * {pri_t} * I_v[l, a]")
    L.append(f"  recover_v_back[l in patch, a in age] : I_v[l, a] --> S[l, a] @ {gamma_v_t} * (1 - {pri_t}) * I_v[l, a]")
    L.append(f"  recover_c[l in patch, a in age] : I_c[l, a] --> R[l, a] @ {gamma_c_t} * I_c[l, a]")
    # Age-split waning of immunity.
    for a in ages:
        L.append(f"  waning_{a}[l in patch] : R[l, {a}] --> S[l, {a}] @ {omega_t[a]} * R[l, {a}]")
    # Aging a_i → a_{i+1} for each compartment.
    for i in range(A - 1):
        a0, a1 = ages[i], ages[i + 1]
        for c in comps:
            L.append(f"  age_{c}_{a0}[l in patch] : {c}[l, {a0}] --> {c}[l, {a1}] @ {aging_t} * {c}[l, {a0}]")
    # Births into the youngest age; per-(comp,age) mortality.
    L.append(f"  birth[l in patch] : --> S[l, {ages[0]}] @ {birth_t} * N_total[l]")
    for a in ages:
        for c in comps:
            L.append(f"  death_{c}_{a}[l in patch] : {c}[l, {a}] --> @ {mu_t[a]} * {c}[l, {a}]")
    # AFP paralysis influx: rho · new I_c force (transmission + reversion), summed
    # over all strata into the single global accumulator (observed as incidence).
    L.append("  afp_influx : --> AFP")
    L.append(f"    @ {rho_t} * sum(l in patch, sum(a in age,")
    L.append(f"        {foi_c}")
    L.append(f"      + {murev_t} * {foi_v}))")
    L.append("}")
    L.append("")

    if observe:
        L.append("observations {")
        L.append("  afp : {")
        L.append("    projected  = incidence(afp_influx)")
        L.append("    every      = 30 'days")
        L.append(f"    likelihood = neg_binomial(mean = projected, r = {k_t})")
        L.append("  }")
        L.append("}")
        L.append("")

    # Initial conditions from population immunity. Susceptibles S0 (per cell) is
    # a PARAMETER so scenarios set the regime: low immunity (high S0) → a
    # self-propagating outbreak; high immunity (low S0) → contained endemic just
    # below the EIP* = 1 - 1/R0 interruption threshold. seed = small planting.
    seed = 5
    if full:
        s_expr = "S0"
        r_expr = f"{pop - 2 * seed} - S0"
    else:
        s0_lit = round((1.0 - immunity) * pop)
        s_expr = str(s0_lit)
        r_expr = str(pop - 2 * seed - s0_lit)
    L.append("init {")
    L.append("  AFP = 0")
    L.append(f"  S[l in patch, a in age] = {s_expr}")
    L.append(f"  I_v[l in patch, a in age] = {seed}")
    L.append(f"  I_c[l in patch, a in age] = {seed}")
    L.append(f"  R[l in patch, a in age] = {r_expr}")
    L.append("}")
    L.append("")
    L.append("simulate {")
    L.append("  from = 0 'days")
    L.append(f"  to   = {to}")
    L.append("}")
    L.append("")

    if full:
        # Two literature-grounded cVDPV2 regimes, switched by initial immunity
        # (S0) and importation (iota). Shared transmission params (type-2 R0~5,
        # ~28-day shedding γ≈1/28, PIR 1:2000) per Thompson/Duintjer Tebbens and
        # the IDM Nigeria model; see tests/recovery/cases/polio_metapop/README.
        s0_outbreak = round(0.45 * pop)   # ~55% immune: under-vaccinated pocket
        s0_endemic  = round(0.10 * pop)   # ~90% immune: contained, above EIP*

        def scenario(name: str, label: str, s0: int, iota_v: str) -> None:
            L.append(f"  {name} {{")
            L.append(f'    label = "{label}"')
            L.append("    set = {")
            L.append("      R0_c = 5.0")
            L.append("      R0_v = 2.0")
            L.append("      gamma_v = 0.0357")
            L.append("      gamma_c = 0.0357")
            L.append("      p_recover_immune = 0.95")
            L.append("      mu_rev = 0.02")
            L.append("      rho_afp = 0.0005")
            L.append("      k = 5.0")
            L.append(f"      iota = {iota_v}")
            L.append(f"      S0 = {s0}")
            if coupling_degree > 0:
                L.append("      kappa = 0.05")
            L.append("      aging_rate = 0.0005")
            L.append("      birth_rate = 0.0001")
            for a in ages:
                L.append(f"      omega_{a} = 0.0002")
            for a in ages:
                L.append(f"      mu_{a} = 0.0002")
            L.append("    }")
            L.append("  }")

        L.append("scenarios {")
        scenario("outbreak",
                 "under-vaccinated outbreak pocket (R_eff>1, R0 identifiable)",
                 s0_outbreak, "0.0")
        scenario("endemic",
                 "contained sub-threshold endemic (opaque, R0 weakly identified)",
                 s0_endemic, "0.0001")
        L.append("}")
        L.append("")

    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--patches", "-P", type=int, required=True)
    ap.add_argument("--ages", "-A", type=int, required=True)
    ap.add_argument("--shape", choices=("seir", "polio"), default="seir",
                    help="seir (default): the SEIR scaling toy (byte-identical "
                         "to prior benches). polio: cVDPV2-shaped metapop faithfully "
                         "mirroring Daniel Klein's Sokoto model (gh#207/#209): S/I_v/I_c/R "
                         "+ AFP, age-mixing FOI, gravity imports, aging/waning/demography")
    ap.add_argument("--to", default="12 'years", metavar="HORIZON",
                    help="[polio] simulate horizon (default '12 \\'years', matching his)")
    ap.add_argument("--immunity", type=float, default=0.8, metavar="FRAC",
                    help="[polio] initial immune fraction (R/N) — high (~0.8-0.9) keeps "
                         "R_eff just above 1, the low-level-endemic cVDPV2 regime")
    ap.add_argument("--iota", type=float, default=0.0, metavar="VAL",
                    help="[polio] external force of infection on the circulating chain "
                         "(imported virus) — prevents full extinction / fadeout-reemergence")
    ap.add_argument("--pop", type=int, default=20010, metavar="N",
                    help="[polio] population per (patch,age) cell")
    ap.add_argument("--coupling", choices=("on", "off"), default="on")
    ap.add_argument("--grad", choices=("full", "minimal"), default="full")
    ap.add_argument("--observe", action="store_true",
                    help="add an observation block (for PMMH/PGAS "
                         "inference profiling); off by default so scaling "
                         "benches stay byte-identical")
    ap.add_argument("--coupling-degree", type=int, default=0, metavar="K",
                    help="sparse ring coupling: each patch couples to its K "
                         "nearest neighbours (rest of W = 0) + a guarded FOI; "
                         "0 (default) = dense all-to-all W (the FOI-blowup shape)")
    ap.add_argument("-o", "--out", type=Path, default=None,
                    help="output .camdl path (default: stdout)")
    args = ap.parse_args()

    if args.shape == "polio":
        text = gen_polio(args.patches, args.ages, args.grad,
                         args.observe, coupling_degree=args.coupling_degree, to=args.to,
                         immunity=args.immunity, iota=args.iota, pop=args.pop)
    else:
        text = gen_camdl(args.patches, args.ages, args.coupling, args.grad, args.observe,
                         coupling_degree=args.coupling_degree)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(text)} bytes)", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
