//! Cross-language deserialisation of the counterfactual-contrasts showcase golden
//! (proposal 2026-06-25).
//!
//! The IR `camdlc` emits for `tests/fixtures/contrasts/contrasts_showcase.camdl`
//! (regenerated by `make update-contrasts-golden`, drift-gated by
//! `make check-contrasts-golden`) must deserialise into the Rust contrast types
//! with the run-rooted operands, the `over [from, to]` window, and the #5 stored
//! quantity `dimension` intact. This pins the OCaml→Rust wire contract for the
//! contrasts IR (stage A/B); the two-arm replay reducer is stage C.

use ir::contrast::{ContrastExpr, RunNamespace};
use ir::expr::BinOp;
use std::path::PathBuf;

fn model() -> ir::Model {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../tests/fixtures/contrasts/ir/contrasts_showcase.ir.json");
    let s = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
    ir::from_str(&s).unwrap_or_else(|e| panic!("deser contrasts_showcase: {e:?}"))
}

#[test]
fn showcase_golden_deserialises_contrast_and_quantity_dimension() {
    let m = model();

    // ── The #5 stored quantity dimension ──
    let total = m.quantities.iter().find(|q| q.name == "total").expect("quantity `total`");
    assert_eq!(
        total.dimension,
        Some((1, 0)),
        "final(D) is a population count (P^1 T^0)"
    );

    // ── The contrast node: averted = no_sia.quantities.total - with_sia.quantities.total ──
    assert_eq!(m.contrasts.len(), 1, "one contrast");
    let c = &m.contrasts[0];
    assert_eq!(c.name, "averted");
    assert_eq!(c.window.from, 140.0, "origin + 20 weeks = day 140");
    assert_eq!(c.window.to, 364.0, "origin + 52 weeks = day 364");

    match &c.body {
        ContrastExpr::BinOp { op: BinOp::Sub, left, right } => {
            match left.as_ref() {
                ContrastExpr::RunMember { run, ns, member } => {
                    assert_eq!(run, "no_sia");
                    assert_eq!(*ns, RunNamespace::Quantities);
                    assert_eq!(member, "total");
                }
                other => panic!("left: expected no_sia.quantities.total, got {other:?}"),
            }
            match right.as_ref() {
                ContrastExpr::RunMember { run, ns, member } => {
                    assert_eq!(run, "with_sia");
                    assert_eq!(*ns, RunNamespace::Quantities);
                    assert_eq!(member, "total");
                }
                other => panic!("right: expected with_sia.quantities.total, got {other:?}"),
            }
        }
        other => panic!("body: expected (no_sia.total - with_sia.total), got {other:?}"),
    }
}
