//! Cross-language deserialisation of the generated-quantities showcase golden
//! (proposal 2026-06-25).
//!
//! The IR `camdlc` emits for `tests/fixtures/quantities/quantities_showcase.camdl`
//! (regenerated by `make update-quantities-golden`, drift-gated by
//! `make check-quantities-golden`) must deserialise into the Rust quantity types
//! with every variant intact: a state series, every value/time reduction, an
//! integral, reduction arithmetic (`Derived`), stratified expansion, and the
//! v1.1 `observations.<stream>` source. This pins the OCaml→Rust wire contract
//! for the quantities IR; the OUTPUT values are pinned by `quantities_surface.rs`.

use ir::expr::BinOp;
use ir::quantity::{QuantityBody, QuantitySource, ScalarExpr, TemporalReduce, TimeReduce, ValueReduce};
use std::path::PathBuf;

fn model() -> ir::Model {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../tests/fixtures/quantities/ir/quantities_showcase.ir.json");
    let s = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
    ir::from_str(&s).unwrap_or_else(|e| panic!("deser quantities_showcase: {e:?}"))
}

/// The first quantity leaf with this name (stratified families share a name).
fn q<'a>(m: &'a ir::Model, name: &str) -> &'a ir::quantity::Quantity {
    m.quantities.iter().find(|q| q.name == name).unwrap_or_else(|| panic!("no quantity `{name}`"))
}

#[test]
fn showcase_golden_deserialises_every_variant() {
    let m = model();
    assert_eq!(m.quantities.len(), 27, "21 state + 2 derived + 4 obs leaves (stratified families expanded)");

    // ── State source: a bare series (reduce = None) ──
    match &q(&m, "total_prev").body {
        QuantityBody::Reduced { source: QuantitySource::State(_), reduce: None } => {}
        other => panic!("total_prev: expected State series, got {other:?}"),
    }

    // ── Value reductions ──
    assert!(matches!(
        &q(&m, "peak_prev").body,
        QuantityBody::Reduced { source: QuantitySource::State(_), reduce: Some(TemporalReduce::Value(ValueReduce::Max)) }
    ));
    assert!(matches!(
        &q(&m, "trough_prev").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Value(ValueReduce::Min)), .. }
    ));
    assert!(matches!(
        &q(&m, "mean_prev").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Value(ValueReduce::Mean)), .. }
    ));
    assert!(matches!(
        &q(&m, "high_days").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Value(ValueReduce::CountAbove(_))), .. }
    ));
    assert!(matches!(
        &q(&m, "low_days").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Value(ValueReduce::CountBelow(_))), .. }
    ));
    assert!(matches!(
        &q(&m, "final_R").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Value(ValueReduce::Final)), .. }
    ));

    assert!(matches!(
        &q(&m, "prev_at_50").body,
        QuantityBody::Reduced {
            reduce:
                Some(TemporalReduce::Value(ValueReduce::ValueAt(
                    ir::quantity::TimeAnchor::Time(_)
                ))),
            ..
        }
    ));
    // Obs-source value_at: the anchor rides the same wire shape.
    assert!(matches!(
        &q(&m, "cases_at_28").body,
        QuantityBody::Reduced {
            source: QuantitySource::Observation { .. },
            reduce:
                Some(TemporalReduce::Value(ValueReduce::ValueAt(
                    ir::quantity::TimeAnchor::Time(_)
                ))),
        }
    ));

    // ── Integral ──
    assert!(matches!(
        &q(&m, "person_days").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Integral), .. }
    ));

    // ── Time reductions ──
    assert!(matches!(
        &q(&m, "peak_t").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Time(TimeReduce::TimeOfMax)), .. }
    ));
    assert!(matches!(
        &q(&m, "trough_t").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Time(TimeReduce::TimeOfMin)), .. }
    ));
    assert!(matches!(
        &q(&m, "onset").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Time(TimeReduce::FirstAbove(_))), .. }
    ));
    assert!(matches!(
        &q(&m, "last_lo").body,
        QuantityBody::Reduced { reduce: Some(TemporalReduce::Time(TimeReduce::LastBelow(_))), .. }
    ));

    // ── Derived: `outbreak_dur = fadeout - onset` over prior scalar QRefs ──
    match &q(&m, "outbreak_dur").body {
        QuantityBody::Derived(ScalarExpr::BinOp { op: BinOp::Sub, left, right }) => {
            assert!(matches!(**left, ScalarExpr::QRef(ref r) if r.name == "fadeout"));
            assert!(matches!(**right, ScalarExpr::QRef(ref r) if r.name == "onset"));
        }
        other => panic!("outbreak_dur: expected Derived(fadeout - onset), got {other:?}"),
    }

    // ── v1.1 observation source: reduce `observations.cases` ──
    match &q(&m, "peak_cases").body {
        QuantityBody::Reduced {
            source: QuantitySource::Observation { stream },
            reduce: Some(TemporalReduce::Value(ValueReduce::Max)),
        } => assert_eq!(stream, "cases"),
        other => panic!("peak_cases: expected max(observations.cases), got {other:?}"),
    }
    assert!(matches!(
        &q(&m, "total_cases").body,
        QuantityBody::Reduced { source: QuantitySource::Observation { .. }, reduce: Some(TemporalReduce::Integral) }
    ));
    match &q(&m, "cases_onset").body {
        QuantityBody::Reduced {
            source: QuantitySource::Observation { stream },
            reduce: Some(TemporalReduce::Time(TimeReduce::FirstAbove(_))),
        } => assert_eq!(stream, "cases"),
        other => panic!("cases_onset: expected first_above(observations.cases, _), got {other:?}"),
    }

    // ── Stratified expansion: one leaf per patch, carrying its stratum cell ──
    let prevalence: Vec<&ir::quantity::Quantity> =
        m.quantities.iter().filter(|q| q.name == "prevalence").collect();
    assert_eq!(prevalence.len(), 2, "prevalence expands to one leaf per patch");
    let levels: std::collections::BTreeSet<&str> = prevalence
        .iter()
        .flat_map(|q| q.stratum.iter().map(|s| s.level.as_str()))
        .collect();
    assert_eq!(levels, ["a", "b"].into_iter().collect(), "patch levels a, b");
}
