//! Cross-language deserialisation of the gh#204 reactive compiler/IR goldens.
//!
//! The IR `camdlc` emits for `tests/fixtures/reactive/*.camdl` (regenerated by
//! `make update-reactive-golden`) must deserialise to `FireSource::Reactive`
//! with the expected `TriggerExpr`. These are compile-only goldens — the runtime
//! rejects an active reactive policy (`REACTIVE_INTERVENTIONS`), so they pin the
//! IR SHAPE and the OCaml→Rust wire contract, not a trajectory.

use ir::intervention::{
    CmpOp, FireSource, ObsReducer, TriggerExpr, TriggerQuantity, TriggerThreshold,
};
use std::path::PathBuf;

fn golden(name: &str) -> ir::Model {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../tests/fixtures/reactive/ir")
        .join(format!("{name}.ir.json"));
    let s = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
    ir::from_str(&s).unwrap_or_else(|e| panic!("deser {name}: {e:?}"))
}

#[test]
fn sir_observed_threshold_golden_is_reactive() {
    let m = golden("reactive_sir_observed_threshold");
    let iv = m.interventions.iter().find(|i| i.name == "sia").expect("sia intervention");
    // gh#204: a reactive policy is kind=Scenario, fire=Reactive.
    assert!(iv.kind.is_scenario());
    let t = match &iv.fire {
        FireSource::Reactive(t) => t,
        FireSource::Scheduled(_) => panic!("expected a reactive fire source"),
    };
    assert_eq!(t.after, 21.0);
    assert!(t.once);
    assert_eq!(t.cooldown, None);
    match &t.when_ {
        TriggerExpr::Cmp {
            lhs: TriggerQuantity::Observed { stream, window, reducer },
            op,
            rhs,
        } => {
            assert_eq!(stream, "weekly_cases");
            assert_eq!(*window, Some(28.0));
            assert_eq!(*reducer, ObsReducer::Sum);
            assert_eq!(*op, CmpOp::Ge);
            assert_eq!(*rhs, TriggerThreshold::Param("trigger_threshold".into()));
        }
        other => panic!("expected `observed >= param`, got {other:?}"),
    }
}

#[test]
fn indexed_patch_golden_expands_and_is_reactive() {
    let m = golden("reactive_indexed_patch_sia");
    let names: Vec<&str> = m.interventions.iter().map(|i| i.name.as_str()).collect();
    assert!(names.contains(&"sia_north"), "stratified to sia_north: {names:?}");
    assert!(names.contains(&"sia_south"), "stratified to sia_south: {names:?}");
    let north = m.interventions.iter().find(|i| i.name == "sia_north").unwrap();
    assert_eq!(north.base_name.as_deref(), Some("sia"), "base_name preserved");
    match &north.fire {
        FireSource::Reactive(t) => match &t.when_ {
            TriggerExpr::Cmp { lhs: TriggerQuantity::Observed { stream, .. }, .. } => {
                assert_eq!(stream, "weekly_cases_north", "indexed stream resolved");
            }
            other => panic!("expected an indexed observed comparison, got {other:?}"),
        },
        FireSource::Scheduled(_) => panic!("expected a reactive fire source"),
    }
    match &north.actions[..] {
        [ir::intervention::Action::FractionTransfer(ft)] => {
            assert_eq!(ft.src, "S_north", "indexed action src");
            assert_eq!(ft.dst, "V_north", "indexed action dst");
        }
        other => panic!("expected one indexed fraction_transfer, got {other:?}"),
    }
}
